### ISSUE TITLE
Consider renaming "Shortcuts" to "Keyboard Shortcuts"

### ISSUE THREAD

**Issue by erwinmaza** [Xcode-Tips/xcode-tips.github.io#12]
Upon landing on the repo page, and scanning the Contents section, I saw an intriguing item called "Shortcuts". 

My first reaction was "Ooh, there are ways to automate Xcode? "

Maybe my brain is weird. Maybe I had just read something related to iOS Shortcuts. In any case, I was thrown off by that title. Please consider disambiguating that section.

**Comment by jessesquires** [comment]
Ha 😄 

Great idea! I would gladly accept a PR. 😊

**Comment by jessesquires** [comment]
finished
