### ISSUE TITLE
Move each section to its own file

### ISSUE THREAD

**Issue by jessesquires** [Xcode-Tips/xcode-tips.github.io#16]
This is not a *huge* problem right now, but it might become one.

We can retain the table of contents. Then for each section, move it to its own file.

For example, "Breakpoints" would move to `/breakpoints.md`

Then *I think* GitHub Pages would produce `xcode-tips.github.io/breakpoints` as the URL.

**Comment by kevnm67** [comment]
@jessesquires are you familiar with [Artsy's README](https://github.com/artsy/README) repo?  It's worth checking out and related to this issue.

**Comment by lordcodes** [comment]
https://nicolas-van.github.io/easy-markdown-to-github-pages/

There is a GitHub Jekyll plugin that you can use on GitHub Pages that converts the relative markdown links to relative links in the generated HTML version of site.

```
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
```

**Comment by jessesquires** [comment]
@lordcodes 

Ah, very nice. So you can write something like the following?

```md
[Breakpoints](breakpoints.md)
```

And that will link to `xcode-tips.github.io/breakpoints`?

**Comment by jessesquires** [comment]
Once [we finish adding the existing tips](https://github.com/Xcode-Tips/xcode-tips.github.io/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+tip+%2B+needs+PR%22), I think it will be a good time to tackle this issue.

**Comment by lordcodes** [comment]
> Ah, very nice. So you can write something like this:
> ```md
> [Breakpoints](breakpoints.md)
> ```
> And that will link to `xcode-tips.github.io/breakpoints`?

I believe it does work like that, would have to try to know for definite.

**Comment by lordcodes** [comment]
It looks like the plugin is activated by default, so you just need to use relative links to the markdown files and it should work by default.
